--- # CES Configuration parameters
spectrometer:
  integration_time: 1000000
  type: "QEPro"
MFC:
  port: "/dev/ttyS4"
  baudrate: 19200
  numMFCs: 1
  unit: "A"
TEC:
  port: "/dev/ttyS1"
  baudrate: 57600
  channel: 1
  setTemp: 23
gpio:
  gpioLocation: "/dev/gpiochip"
  lineParams: #note: use gpioinfo to find the board numbers and offsets of desired pins
    "SSR1":
      "board": "0"
      "offset": 28
    "SSR2": 
      "board": "0"
      "offset": 18
    "LED": 
      "board": "1"
      "offset": 6
analog:
  #Therm:
  A: 1.13206975726444e-03
  B: 2.33431080526447e-04
  C: 9.43470416157594e-08
  D: -2.63722384777803e-11 
  #Press:
  Pres_Offset: -134.64
  Pres_Slope: 280.62
  numAnalog: 6
UDP:
  IP: "192.168.7.2"
  # IP: "127.0.0.1"
  port: 12345
  buffer_size: 4096
save:
  minToSave: 0.3
  # location: "/home/carrie/Documents/Programming/Python/pyCES/Data"
  location: "/home/debian/Data"
