--- # CES Configuration parameters
spectrometer:
  integration_time: 1000000
  type: "QEPro"
MFC:
  port: "ttyS2"
  baudRate: 38400
  numMFCs: 1
TEC:
  port: "ttyS1"
  baudRate: 57600
valves:
  numValves: 2
analog:
  #Therm:
  A: 1.13206975726444e-03
  B: 2.33431080526447e-04
  C: 9.43470416157594e-08
  D: -2.63722384777803e-11 
  #Press:
  Pres_Offset: -134.64
  Pres_Slope: 280.62
  numAnalog: 6
UDP:
  #IP: "192.168.7.2"
  IP: "127.0.0.1"
  port: 12345
  buffer_size: 4096
save:
  minToSave: 0.3
  location: "/home/carrie/Documents/Programming/Python/pyCES/Data"
  #location: "/home/debian/Data"
